version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: todo-api:1.0.1
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root!@34
      POSTGRES_DB: todo_api
      JWT_SECRET: "jwt_secret_1234"
    ports:
      - "8080:8080"
    networks:
      - net
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:14.19-alpine
    environment:
      POSTGRES_DB: todo_api
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root!@34
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d todo_api"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

networks:
  net:
    driver: bridge
